config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "articles#index"

  resources :articles do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  include Visible

  has_one_attached :image, dependent: :destroy
  has_many :comments, dependent: :destroy
  belongs_to :author, class_name: 'User'

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }

  scope :ordered_by_desc, -> (direction = :desc) { order(created_at: direction)}
  scope :ordered_by_asc, -> (direction = :asc) { order(created_at: direction)}
  scope :ordered_by_title, -> (direction = :asc) { order(title: direction)}
  scope :with_authors, -> {includes(:author)}
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :author, class_name: 'User'
end

app/models/concerns/visible.rb
module Visible
  extend ActiveSupport::Concern

  VALID_STATUSES = ['public', 'private', 'archived']

  included do
    validates :status, inclusion: { in: VALID_STATUSES }
  end

  class_methods do
    def public_count
      where(status: 'public').count
    end
  end

  def archived?
    status == 'archived'
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, foreign_key: :author_id, dependent: :destroy   
  validates :username, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    include Pundit

    rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

    protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    end

  end
  

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :authenticate_user!, only: %i[new create edit update destroy]
    before_action :set_article, only: %i[show edit update destroy]

    # http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]
    # def index
    #   if param[:sort] == "Title"
    #     @articles = Article.ordered.with_authors.paginate(page: params[:page], per_page: 2).where('title LIKE ?', "#{params[:search]}%")
    #   @articles = Article.ordered.with_authors.paginate(page: params[:page], per_page: 2).where('title LIKE ?', "#{params[:search]}%")
    # end
  def index
    @sort_type = params.fetch(:sort_type, "latest")
    @articles = Article.with_authors.paginate(page: params[:page], per_page: 3).where('title LIKE ?', "#{params[:search]}%")
    if @sort_type == "title"
      @articles = @articles.ordered_by_title
    elsif @sort_type == "oldest"
      @articles = @articles.ordered_by_asc
    else 
      @articles = @articles.ordered_by_desc
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    @article.author = current_user

    unless article_params[:image].nil?
      image = Cloudinary::Uploader.upload(article_params[:image], options = {})
    end

    if @article.save
      redirect_to @article
    else
      render :new
    end
  end

  def edit
    authorize @article = Article.find(params[:id])
  end

  def update
    authorize @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit
    end
  end

  def destroy
    authorize @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path
  end

  private
  def article_params
    params.require(:article).permit(:title, :body, :status, :image)
  end

  def set_article
    @article = Article.find(params[:id])
  end

  def authorize_user!
    return if @article.author_id == current_user.id

    redirect_to :articles,
                alert: "You are not allowed to perform this acrion"
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!, only: %i[create destroy]
      # http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy

    def create
      @article = Article.find(params[:article_id])
      @comment = @article.comments.create(params[:comment].permit(:body).merge(author_id: current_user.id))
      redirect_to article_path(@article)
    end
  
    def destroy
      @article = Article.find(params[:article_id])
      @comment = @article.comments.find(params[:id])
      authorize @comment
      @comment.destroy
      redirect_to article_path(@article)
    end
  
    private
      def comment_params
        params.require(:comment).permit(:commenter, :body, :status)
      end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :image %><br>
    <%= form.file_field :image %><br>
  </div>

  <div>
    <%= form.label :status %><br>
    <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

<%= link_to 'Show', articles_path %>
<%= link_to 'Back', @article %>

app/views/articles/index.html.erb
<br><br>
<%= form_tag(articles_path, method: :get) do %>
  <%= text_field_tag(:search, params[:search]) %>
  <%= submit_tag("Search") %>
<% end %>

<h1>Articles</h1>
Our blog has <%= Article.public_count %> articles and counting!

<p>
<strong>Order: </strong>
  <%= link_to "latest", articles_path(sort_type: 'latest') %>
  <%= link_to "oldest", articles_path(sort_type: 'oldest') %>
  <%= link_to "by title", articles_path(sort_type: 'title') %>
</p>

<ul>
  <% @articles.each do |article| %>
    <% unless article.archived? %>
      <li>
        <%= link_to article.title, article %>
      </li>
    <% end %>
  <% end %>
</ul>
<%= will_paginate @articles %>
<br>
<%= link_to "New Article", new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render "form", article: @article %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p><%= @article.body %></p>

<% if @article.image.present? %>
   <div style="width:400px;">
    <%= image_tag(@article.image, style:'width:100%') %>
  </div>
<% end %>

<% if @article.author.present? %>
<p>
  <strong>Author: </strong>
  <i><%= @article.author.username %></i>
</p>
<% end %>

<ul>
  <% if policy(@article).update? %>
    <li><%= link_to "Edit", edit_article_path(@article) %></li>
  <% end %>
  <% if policy(@article).destroy? %>
  <li><%= link_to "Destroy", article_path(@article),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %></li>
  <% end %>
</ul>

<h2>Comments</h2>
<%= render @article.comments %>


<h2>Add a comment:</h2>
<%= render 'comments/form' %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.author.username %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<% if policy(comment).destroy? %>
<p>
  <%= link_to 'Destroy Comment', [comment.article, comment],
              method: :delete,
              data: { confirm: "Are you sure?" } %>
</p>
<% end %>

app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>

  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%if user_signed_in? %>
        <%= current_user.email %>
        <%= link_to 'Log out', destroy_user_session_path, method: :delete, data: {confirm: 'Are you sure ?'} %>
      <% else %>
        <%= link_to 'Log in', new_user_session_path %>
      <% end %>
    </header>
    <p><%= notice %></p>
    <p><%= alert %></p>
  <%= link_to 'Home', articles_path %>
  <%= yield %>
  </body>
</html>